### ISSUE TITLE
others，其他接口函数

### ISSUE THREAD

**Issue by wingfish** [chinapnr/COVID-19-data#25]
建议 pop 人口函数同样放到 others 接口。
增加一个函数，可以返回所有数据库中的 region。
增加一个函数，可以指定 region，返回所有其下的 area。

**Comment by rexyan** [comment]
### other/region_list 

| 环境     | HTTP请求地址         | 备注 |
| -------- | -------------------- | ---- |
| 测试     | /api/v1/other/region_list |      |
| 访问方式 | GET                  |      |
| 请求头   | Token                |      |

**返回示例**

```json
{
  "data": [
    "China", 
    "US"
  ], 
  "message": "success", 
  "return_code": "90000"
}
```



### other/area_list

| 环境     | HTTP请求地址       | 备注 |
| -------- | ------------------ | ---- |
| 测试     | /api/v1/other/area_list |      |
| 访问方式 | GET                |      |
| 请求头   | Token              |      |

**URL 参数**

| 名称   | 类型   | 是否必须 | 其他限制 | 描述     |
| ------ | ------ | -------- | -------- | -------- |
| region | String | 是       |          | 国家名称 |

**返回示例**

```json
{
  "data": [
    "Chongqiong", 
    "Anhui"
  ], 
  "message": "success", 
  "return_code": "90000"
}
```



### other/population

| 环境     | HTTP请求地址              | 备注 |
| -------- | ------------------------- | ---- |
| 测试     | /api/v1/other/populations |      |
| 访问方式 | GET                       |      |
| 请求头   | Token                     |      |

**URL 参数**

| 名称   | 类型   | 是否必须 | 其他限制    | 描述     |
| ------ | ------ | -------- | ----------- | -------- |
| region | String | 否       |             | 国家名称 |
| year   | String | 是       | 默认为 2020 | 年份     |

**返回示例**

```json
{
  "code": "90000",
  "message": "success",
  "data": [
    {
      "name": "China",
      "population_num": 1400050000
    }
  ]
```
