### ISSUE TITLE
v1.1 功能列表

### ISSUE THREAD

**Issue by zhangmuqing** [chinapnr/COVID-19-data#28]
1.  文档页和swagger页去掉健康检查接口/api​/v1​/healthHealth
2. /api/v1/infection/region不输入日期返回数据库中最新一天的记录
3. /api​/v1​/infection​/region​/detail不输入日期返回数据库中最新一天的记录
4. /api/v1/infection/area不输入日期返回数据库中最新一天的记录
5. 增加数据校验，每日更新数据后对数据库中的area字段设置阈值，小于阈值报警
6.  文档页和swagger页增加接口说明

**Comment by wingfish** [comment]
几个建议：
1 github 项目页增加英文版本说明
2 日期输入范围，增加一个参数，last days = n，n 介于 1-10，返回最近 10 天的数据
3 日期输入，增加一个 month参数，202002，就返回 2020 年 2 月的数据，实际使用这样会比较容易
4 直接调用 global 接口，返回的不知道是什么日期，返回参数中要增加日期。（这个我已经说了好几次了，一些如日期、region、area 在返回中要再带一下，比如带日期，就可以方便一些程序自动操作）

**Comment by zhangmuqing** [comment]
2和3建议在sdk层做，接口做整个逻辑和开始结束时间就冲突了。

**Comment by wingfish** [comment]
好的，那么合并一下，我没意见了。ut 尽快达到一定覆盖率。

**Comment by rexyan** [comment]
```json
{
  "code": "90000",
  "message": "success",
  "data": {
    "global": {
      // 在此处新增 last_update_date 字段
      "last_update_date ": "2020-04-09",
      "confirmed_add": 1475773,
      "deaths_add": 86626,
      "recovered_add": 323390,
      "country": {
        "Afghanistan": {
          "confirmed_add": 443,
          "deaths_add": 14,
          "recovered_add": 29
        }
      }
    }
  }
}
```

**Comment by wingfish** [comment]
这个是否可以close了
