### ISSUE TITLE
v1.2 接口日期相关修改

### ISSUE THREAD

**Issue by zhangmuqing** [chinapnr/COVID-19-data#36]
1. 输入开始日期，不输入结束日期，返回开始日期的当天数据
2. 不输入开始日期，输入结束日期，报错

**Comment by rexyan** [comment]
1.2 版本时间逻辑如下：
- 只输入 start_date:
   - 不大于当天日期： 查询当天日期
   - 大于当天日期：提示错误
- 只输入 end_date:
   - 提示错误
- 既输入 start_date 也输入 end_date:
  - 日期跨度不大于 10 天： 正常查询
  - 日期跨度大于 10 天： 提示错误
  - 日期跨度为负数（end_date 小于 start_date ）：提示错误
- 两者均不输入:
  - 查询最新日期数据
- 格式不正确（例如 2020-02-31，2020-2-28）：提示错误

**Comment by wingfish** [comment]
这些是否在 v1.2 都被修复了？
