### ISSUE TITLE
信息整理，接口列表信息

### ISSUE THREAD

**Issue by rexyan** [chinapnr/COVID-19-data#4]
#### 接口列表信息 v1.0

- [ ] 查询治愈-死亡的比例
- [ ] 查询每日新增情况
- [ ] 查询发生过疫情的国家和地区
- [ ] 查询当前疫情的热点信息
- [ ] 查询疫苗研制进度信息
- [ ] 查询每个国家数据 [确诊，治愈，死亡，治疗]
- [ ] 查询每个国家每个城市的数据 [确诊，治愈，死亡，治疗，天气]
- [ ] 查询每个大洲每个国家的数据 [确诊，治愈，死亡，治疗]

**Comment by rexyan** [comment]
#### 接口设计信息

| 接口名称                                                  | 过滤条件       |
| --------------------------------------------------------- | -------------- |
| 查询治愈-死亡的比例                                       | 时间区间，地区 |
| 查询每日新增情况                                          | 地区           |
| 查询发生过疫情的国家和地区                                | 时间区间       |
| 查询每个国家数据 [确诊，治愈，死亡，治疗]                 | 时间区间       |
| 查询每个国家每个城市的数据 [确诊，治愈，死亡，治疗，天气] | 时间区间       |
| 查询每个大洲每个国家的数据 [确诊，治愈，死亡，治疗]       | 时间区间       |



### 接口设计

#### 1. 查询感染年龄分布 (支持按照时间区间和地区过滤)

***

| 环境       | HTTP请求地址   | 备注         |
| ---------- | -------------- | ------------ |
| 生产       | /api/ratio/age |              |
| 访问方式   | GET            |              |
| 请求头信息 | Token          | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制                              | 描述     |
| ----- | ------ | -------- | ------------------------------------- | -------- |
| area  | String | 否       | 相关编码可通过接口 6 获取，默认为全国 | 地区编码 |
| stime | String | 否       | 默认值为当前时间前七天                | 开始时间 |
| etime | String | 否       | 默认值为当前时间                      | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/ratio/age?country=China&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": [
    "string"
  ]
}
```



#### 2. 查询和 sars 的对比数据  (支持按照时间区间和地区过滤)

| 环境       | HTTP请求地址    | 备注         |
| ---------- | --------------- | ------------ |
| 生产       | /api/ratio/sars |              |
| 访问方式   | GET             |              |
| 请求头信息 | Token           | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制                              | 描述     |
| ----- | ------ | -------- | ------------------------------------- | -------- |
| area  | String | 否       | 相关编码可通过接口 6 获取，默认为全国 | 地区编码 |
| stime | String | 否       | 默认值为当前时间前七天                | 开始时间 |
| etime | String | 否       | 默认值为当前时间                      | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/ratio/sars?country=China&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "sars": "string",
    "ncov": "string"
  }
}
```



#### 3. 查询患病男女比例 (支持按照时间区间和地区过滤)

| 环境       | HTTP请求地址      | 备注         |
| ---------- | ----------------- | ------------ |
| 生产       | /api/ratio/gender |              |
| 访问方式   | GET               |              |
| 请求头信息 | Token             | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制                              | 描述     |
| ----- | ------ | -------- | ------------------------------------- | -------- |
| area  | String | 否       | 相关编码可通过接口 6 获取，默认为全国 | 地区编码 |
| stime | String | 否       | 默认值为当前时间前七天                | 开始时间 |
| etime | String | 否       | 默认值为当前时间                      | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/ratio/gender?country=China&stime=20200326&etime=20200319" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "male": "string",
    "female": "string"
  }
}
```



#### 4. 查询治愈-死亡的比例 (支持按照时间区间和地区过滤)

| 环境       | HTTP请求地址              | 备注         |
| ---------- | ------------------------- | ------------ |
| 生产       | /api/ratio/rehabilitation |              |
| 访问方式   | GET                       |              |
| 请求头信息 | Token                     | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制                              | 描述     |
| ----- | ------ | -------- | ------------------------------------- | -------- |
| area  | String | 否       | 相关编码可通过接口 6 获取，默认为全国 | 地区编码 |
| stime | String | 否       | 默认值为当前时间前七天                | 开始时间 |
| etime | String | 否       | 默认值为当前时间                      | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/ratio/rehabilitation?country=China&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "cure": "string",
    "death": "string"
  }
}
```



#### 5. 查询每日新增情况 (支持按照地区过滤)

| 环境       | HTTP请求地址         | 备注         |
| ---------- | -------------------- | ------------ |
| 生产       | /api/infection/daily |              |
| 访问方式   | GET                  |              |
| 请求头信息 | Token                | 用户认证信息 |

**URL 参数**

| 名称 | 类型   | 是否必须 | 其他限制                              | 描述     |
| ---- | ------ | -------- | ------------------------------------- | -------- |
| area | String | 否       | 相关编码可通过接口 6 获取，默认为全国 | 地区编码 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/infection/daily?country=China" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "additionalProp1": {
      "diagnose": 0,
      "cure": 0,
      "death": 0,
      "treatment": 0,
      "weather": "string"
    },
    "additionalProp2": {
      "diagnose": 0,
      "cure": 0,
      "death": 0,
      "treatment": 0,
      "weather": "string"
    },
    "additionalProp3": {
      "diagnose": 0,
      "cure": 0,
      "death": 0,
      "treatment": 0,
      "weather": "string"
    }
  }
}
```



#### 6. 查询发生过疫情的国家和地区（支持按照时间区间过滤）

| 环境       | HTTP请求地址        | 备注         |
| ---------- | ------------------- | ------------ |
| 生产       | /api/infection/area |              |
| 访问方式   | GET                 |              |
| 请求头信息 | Token               | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/infection/area?stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "globals": {
      "additionalProp1": {
        "name": "string",
        "code": "string",
        "country": {
          "additionalProp1": {
            "name": "string",
            "code": "string",
            "city": [
              {
                "name": "string",
                "code": "string"
              }
            ]
           }
          ....
        }
      }
    }
  }
}
```



#### 7. 查询当前疫情的热点信息（支持按照时间区间过滤）

| 环境       | HTTP请求地址  | 备注         |
| ---------- | ------------- | ------------ |
| 生产       | /api/news/hot |              |
| 访问方式   | GET           |              |
| 请求头信息 | Token         | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 8. 查询当前疫情的辟谣信息（支持按照时间区间过滤）

| 环境       | HTTP请求地址   | 备注         |
| ---------- | -------------- | ------------ |
| 生产       | /api/news/fake |              |
| 访问方式   | GET            |              |
| 请求头信息 | Token          | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 9. 查询疫苗研制进度信息（支持按照时间区间过滤）

| 环境       | HTTP请求地址      | 备注         |
| ---------- | ----------------- | ------------ |
| 生产       | /api/news/vaccine |              |
| 访问方式   | GET               |              |
| 请求头信息 | Token             | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 10. 查询每个国家数据 [确诊，治愈，死亡，治疗] (支持按照时间区间过滤)

| 环境       | HTTP请求地址           | 备注         |
| ---------- | ---------------------- | ------------ |
| 生产       | /api/infection/country |              |
| 访问方式   | GET                    |              |
| 请求头信息 | Token                  | 用户认证信息 |

**URL 参数**

| 名称    | 类型   | 是否必须 | 其他限制                                  | 描述     |
| ------- | ------ | -------- | ----------------------------------------- | -------- |
| country | String | 否       | 相关编码可通过接口 6 获取，默认为所有国家 | 国家编码 |
| stime   | String | 否       | 默认值为当前时间前七天                    | 开始时间 |
| etime   | String | 否       | 默认值为当前时间                          | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/infection/country?country=China&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "city": [
      {
        "name": "string",
        "code": "string",
        "diagnose": 0,
        "cure": 0,
        "death": 0,
        "treatment": 0,
        "weather": "string"
      }
    ]
  }
}
```



#### 11. 查询每个国家每个城市的数据 [确诊，治愈，死亡，治疗，天气] (支持按照时间区间过滤)

| 环境       | HTTP请求地址        | 备注         |
| ---------- | ------------------- | ------------ |
| 生产       | /api/infection/city |              |
| 访问方式   | GET                 |              |
| 请求头信息 | Token               | 用户认证信息 |

**URL 参数**

| 名称    | 类型   | 是否必须 | 其他限制                                        | 描述     |
| ------- | ------ | -------- | ----------------------------------------------- | -------- |
| country | String | 否       | 相关编码可通过接口 6 获取，默认为所有国家       | 国家编码 |
| city    | String | 否       | 相关编码可通过接口 6 获取，默认为该国家所有地区 | 地区编码 |
| stime   | String | 否       | 默认值为当前时间前七天                          | 开始时间 |
| etime   | String | 否       | 默认值为当前时间                                | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/infection/city?country=China&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "name": "string",
    "code": "string",
    "diagnose": 0,
    "cure": 0,
    "death": 0,
    "treatment": 0,
    "weather": "string"
  }
}
```



#### 12. 查询每个大洲每个国家的数据 [确诊，治愈，死亡，治疗] (支持按照时间区间过滤)

| 环境       | HTTP请求地址          | 备注         |
| ---------- | --------------------- | ------------ |
| 生产       | /api/infection/global |              |
| 访问方式   | GET                   |              |
| 请求头信息 | Token                 | 用户认证信息 |

**URL 参数**

| 名称    | 类型   | 是否必须 | 其他限制                                        | 描述     |
| ------- | ------ | -------- | ----------------------------------------------- | -------- |
| global  | String | 否       | 相关编码可通过接口 6 获取，默认为所有大洲       | 洲编码   |
| country | String | 否       | 相关编码可通过接口 6 获取，默认为该大洲所有国家 | 国家编码 |
| stime   | String | 否       | 默认值为当前时间前七天                          | 开始时间 |
| etime   | String | 否       | 默认值为当前时间                                | 截止时间 |

##### 请求示例

```shell
curl -X GET "http://127.0.0.1:8001/api/infection/global?area=asia&stime=20200319&etime=20200326" -H "accept: application/json"
```

##### 返回示例

```json
{
  "code": "string",
  "response_id": "string",
  "data": {
    "globals": {
      "additionalProp1": {
        "name": "string",
        "code": "string",
        "country": {
          "additionalProp1": {
            "name": "string",
            "code": "string",
            "city": [
              {
                "name": "string",
                "code": "string",
                "diagnose": 0,
                "cure": 0,
                "death": 0,
                "treatment": 0,
                "weather": "string"
              }
             ....
            ]
          }
        }
      }
    }
  }
}
```



#### 13. 查询其他平台 [例如邮轮] 段时间内的数据 [确诊，治愈，死亡，治疗]



#### 14. 查询捐赠情况（支持按照时间区间过滤）

| 环境       | HTTP请求地址     | 备注         |
| ---------- | ---------------- | ------------ |
| 生产       | /api/news/donate |              |
| 访问方式   | GET              |              |
| 请求头信息 | Token            | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 15. 查询奥运会新闻咨询（支持按照时间区间过滤）

| 环境       | HTTP请求地址      | 备注         |
| ---------- | ----------------- | ------------ |
| 生产       | /api/news/olympic |              |
| 访问方式   | GET               |              |
| 请求头信息 | Token             | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 16. 查询股市行情信息（支持按照时间区间和过滤过滤）

| 环境       | HTTP请求地址    | 备注         |
| ---------- | --------------- | ------------ |
| 生产       | /api/news/stock |              |
| 访问方式   | GET             |              |
| 请求头信息 | Token           | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```



#### 17. 查询消费数据, 或者能侧面反映消费的数据（支持按照时间区间和过滤过滤）

| 环境       | HTTP请求地址          | 备注         |
| ---------- | --------------------- | ------------ |
| 生产       | /api/news/consumption |              |
| 访问方式   | GET                   |              |
| 请求头信息 | Token                 | 用户认证信息 |

**URL 参数**

| 名称  | 类型   | 是否必须 | 其他限制               | 描述     |
| ----- | ------ | -------- | ---------------------- | -------- |
| stime | String | 否       | 默认值为当前时间前七天 | 开始时间 |
| etime | String | 否       | 默认值为当前时间       | 截止时间 |

##### 请求示例

```shell

```

##### 返回示例

```json

```

**Comment by wingfish** [comment]
这个是否可以close了？

以后一个issue 就放一个接口功能，不要那么多在一起。issue 尽量带上milestone 也就是这里是版本的标签。
